export const projects = [
  {
    id: 1,
    title: "Simplicity of Living",
    description: "divandivan",
    slug: "simplicity-of-living",
    media: "/images/portfolio1.png",
    media_animation: "/images/portfolio-animation1.png",
    details: {
      client: "Trial and error",
      location: "New york",
      time: "nov 2022",
    },
    stuff: {
      art_director: "sophie amelie",
      photographer: "sophie amelie",
      makeup: "gracy jones",
      costumes: ["sophie amelie"],
    },
    type: "personal",
  },
  {
    id: 2,
    title: "Enrichment",
    description: "sloun",
    slug: "becoming-you",
    media: "/images/portfolio2.png",
    media_animation: "/images/portfolio-animation2.png",
    details: {
      client: "Trial and error",
      location: "Berlin",
      time: "nov 2021",
    },
    stuff: {
      art_director: "sophie amelie",
      photographer: "sophie amelie",
      makeup: "gracy jones",
      costumes: ["sophie amelie", "gracy jones"],
    },
    type: "commercial",
  },
  {
    id: 3,
    title: "Becoming you",
    description: "floskula",
    slug: "enrichment",
    media: "/images/portfolio3.png",
    media_animation: "/images/portfolio-animation3.png",
    details: {
      client: "Trial and error",
      location: "Berlin",
      time: "nov 2021",
    },
    stuff: {
      art_director: "sophie amelie",
      photographer: "sophie amelie",
      makeup: "gracy jones",
      costumes: ["sophie amelie"],
    },
    type: "personal",
  },
  {
    id: 4,
    title: "Classic as chanel",
    description: "divandivan",
    slug: "classic-as-chanel",
    media: "/images/portfolio4.png",
    media_animation: "/images/portfolio-animation4.png",
    details: {
      client: "Trial and error",
      location: "Dublin",
      time: "nov 2019",
    },
    stuff: {
      art_director: "sophie amelie",
      photographer: "sophie amelie",
      makeup: "gracy jones",
      costumes: ["sophie amelie", "gracy jones"],
    },
    type: "commercial",
  },
  {
    id: 5,
    title: "Waking Life",
    description: "floskula",
    slug: "waking-life",
    media: "/images/portfolio5.png",
    media_animation: "/images/portfolio-animation5.png",
    details: {
      client: "Trial and error",
      location: "Tokyo",
      time: "nov 2020",
    },
    stuff: {
      art_director: "sophie amelie",
      photographer: "sophie amelie",
      makeup: "gracy jones",
      costumes: ["sophie amelie", "gracy jones"],
    },
    type: "commercial",
  },
  {
    id: 6,
    title: "Champagne",
    description: "doingwork",
    slug: "champagne",
    media: "/images/portfolio6.png",
    media_animation: "/images/portfolio-animation6.png",
    details: {
      client: "Trial and error",
      location: "Amsterdam",
      time: "nov 2020",
    },
    stuff: {
      art_director: "sophie amelie",
      photographer: "sophie amelie",
      makeup: "gracy jones",
      costumes: ["gracy jones"],
    },
    type: "personal",
  },
];
